server:
  port: 8004

spring:
  application:
    name: category

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 1000ms
      quiet-period: 500ms

  datasource:
    url: ${DB_CATEGORY_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_EXTERNAL_AUTH_SERVER_URL:}/realms/${KC_REALM:}
          jwk-set-uri: ${KC_AUTH_SERVER_URL}/realms/${KC_REALM}/protocol/openid-connect/certs

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

application:
  config:
    account-service-url: ${ACCOUNT_SERVICE_URL}

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
